# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.5

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  execute-cloudformation:
    executor: aws-cli/default
    steps:
        - checkout
        - aws-cli/setup:
            aws-access-key-id: AWS_ACCESS_KEY_ID
            aws-region: AWS_DEFAULT_REGION
            aws-secret-access-key: AWS_SECRET_ACCESS_KEY
        - run:
            name: deploy Cloudformation
            command: |
              set -x
              aws cloudformation deploy --template-file cloudformation/stack.yml --stack-name stackFromCircleCI

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  circleci-live-demo-20230415-workflow:
    jobs:
      - execute-cloudformation
